name: cumbialive
description: © 2021 Cumbia Live.

publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basics
  http: ^0.13.4
  url_launcher: ^6.0.18
  flutter_alert: ^0.4.0
  mask_text_input_formatter: ^2.1.0
  date_format: ^2.0.5
  shimmer: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  image_picker: ^0.8.4+5
  permission_handler:
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  cached_network_image: ^3.2.0
  android_intent: ^2.0.2
  percent_indicator: ^4.0.0
  toggle_switch: ^1.4.0
  dotted_border: ^2.0.0+2
  menu_button: ^1.4.2+1
  country_code_picker: ^2.0.2
  flutter_local_notifications:
  syncfusion_flutter_pdfviewer: ^19.4.48-beta

  
  intl_phone_number_input: ^0.7.0+2
  
  # Agora
  agora_rtc_engine: ^4.2.0

  # Firebase
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6
  firebase_messaging:
  firebase_admin:

  # Icons
  cupertino_icons: ^1.0.4
  material_design_icons_flutter: ^5.0.6595

  # Purchases
  purchases_flutter: ^3.9.3
  in_app_purchase: ^0.5.1+2

  # Lottie
  lottie: ^1.2.1

  geocoder: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/trm.pdf
    - animations/